# For Fleet Free:
# - This file updates policies, queries, agent_options, and controls for all hosts.

# For Fleet Premium:
# - This file updates policies and queries that run on all hosts ("All teams").
# - Remove "controls" and add this to your YAML files in teams/ instead.

policies:
queries:
agent_options:
  path: ./lib/agent-options.yml
controls: # This cannot be set here and in no-team.yml
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: Luis Test
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
  features:
    enable_host_users: true
    enable_software_inventory: true
  webhook_settings:
    activities_webhook:
     enable_activities_webhook: true
     destination_url: https://webhook.site/58703314-75b6-4235-b8b2-b731c384973b
